//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ComputerApp.Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ComputerStoreEntities : DbContext
    {
        public ComputerStoreEntities()
            : base("name=ComputerStoreEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }

        private static ComputerStoreEntities _context;

        public static ComputerStoreEntities GetContext()
        {
            if (_context == null) _context = new ComputerStoreEntities();
            return _context;
        }

        public virtual DbSet<Buyer> Buyers { get; set; }
        public virtual DbSet<Component> Components { get; set; }
        public virtual DbSet<Computer> Computers { get; set; }
        public virtual DbSet<Order> Orders { get; set; }
        public virtual DbSet<ShoppingCart> ShoppingCarts { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
    }
}
