//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ComputerApp.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        public int ОrderID { get; set; }
        public Nullable<int> BuyersID { get; set; }
        public Nullable<System.DateTime> OrderDate { get; set; }
        public Nullable<decimal> OrderPrice { get; set; }
        public string BuyersFIO { get; set; }
        public string BuyersPhone { get; set; }
        public string BuyersAdress { get; set; }
    
        public virtual Buyer Buyer { get; set; }
    }
}
